[pytest]
testpaths = tests

addopts =
    -v
    --html=reports/pytest_report.html
    --self-contained-html
    --junitxml=reports/junit.xml

log_cli = true
log_cli_level = INFO

markers =
    smoke: Smoke tests
    regression: Regression tests

base_url = https://www.saucedemo.com